// config/index.tsx
import { cookieStorage, createStorage, http } from 'wagmi' // Use 'wagmi' directly (Wagmi v2+)
import { WagmiAdapter } from '@reown/appkit-adapter-wagmi'
import { base, arbitrum } from 'wagmi/chains' // ✅ USE WAGMI CHAINS, NOT APPKIT
import type { Chain } from 'viem' // Import Chain type for explicit typing

// Read Project ID from environment variables and trim any whitespace/newlines
export const projectId = process.env.NEXT_PUBLIC_PROJECT_ID?.trim()

// Ensure Project ID is defined at build time
if (!projectId) {
  throw new Error('NEXT_PUBLIC_PROJECT_ID is not defined. Please set it in .env.local')
}

// Define supported networks: Base and Arbitrum for USDC gaming
export const networks: [Chain, ...Chain[]] = [base, arbitrum]

// Create the Wagmi adapter instance
export const wagmiAdapter = new WagmiAdapter({
  storage: createStorage({ storage: cookieStorage }), // Use cookieStorage for SSR
  ssr: true, // Enable SSR support
  projectId,
  networks, // Pass the explicitly typed networks array
})

// Export the Wagmi config generated by the adapter
export const config = wagmiAdapter.wagmiConfig

